### ISSUE TITLE
Как поменять шаблон?

### ISSUE THREAD

**Issue by mihai9621** [xxhax-team/vk-phishing#13]
Можно ли изменить внешний вид шаблона ?

**Comment by AlexXanderGrib** [comment]
### Легко

1) Берёшь файлы шаблона, кладёшь их в папку `static`, так чтобы существовал файл `static/index.html` 
2) Прописываешь в нём ссылку на вход - `/auth`. 
3) Перезапускаешь фишинг
4) Profit!

Если хочешь, чтобы была кастомная страница успешного входа, то в конфиге(файл `config.yml`) меняешь 
```yaml
exit: https://vk.com/im
```
на 
```yaml
exit: /<путь к страничке успешного входа>
```
