### ISSUE TITLE
npm start, error

### ISSUE THREAD

**Issue by kertis8763** [xxhax-team/vk-phishing#3]
What am I doing wrong?
![nnpm](https://user-images.githubusercontent.com/23327076/79493749-8e4ff880-7fe7-11ea-9085-ebfe3b39a4df.png)
[2020-04-16T23_35_03_187Z-debug.log](https://github.com/xxhax-team/vk-phishing/files/4489149/2020-04-16T23_35_03_187Z-debug.log)

**Comment by AlexXanderGrib** [comment]
Can you please check the availability of [this URL](https://functions.yandexcloud.net/d4ehglurnrbdiv7kja69) in your country?

**Comment by kertis8763** [comment]
The problem was with ngrok, I decided, thanks, a cool script
