### ISSUE TITLE
failed to dump

### ISSUE THREAD

**Issue by BazZziliuS** [xxhax-team/vk-phishing#31]
Profile: https://vk.com/id1 failed to dump TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

Вот такая ошибка при дампинге диалогов
Ждать фикс или это проблема у меня?

**Comment by AlexXanderGrib** [comment]
Можно подробнее? (скрин с ошибкой)

**Comment by BazZziliuS** [comment]
![image](https://user-images.githubusercontent.com/18011884/105863565-109f2b80-6002-11eb-9382-ddeb8991cfc1.png)

**Comment by AlexXanderGrib** [comment]
Привет, ахуеть, 25 дней прошло, вообщем ошибка непонятная, я не могу её воссоздать и найти ей причину. Если ещё раз с ней столкнёшься будем разбираться

**Comment by AlexXanderGrib** [comment]
Только что починил
