### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by Strannik74** [xxhax-team/vk-phishing#8]
Module for sending logs to TG, uncomment to enable
Doesn't send logs

telegram: # Module for telegram, uncommment for enable
    token: [XXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXX] # Telegram bot token, got from BotFather
    chatId: [XXXXXXXXXXX] # Contact name, user id or chat id
    lang: ru # Or ru, if you drink vodka
    successOnly: true # Set false, if you want receive unsuccessful messages

**Comment by AlexXanderGrib** [comment]
`chatId` and `token` must be without square brakets.
And if you want to see log in attempts, you must set 
```yaml
successOnly: false
```

**Comment by Strannik74** [comment]
Good evening
Changed configuration
Telegram logs do not come
 
   telegram: # Module for telegram, uncommment for enable
    token: XXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXX # Telegram bot token, got from BotFather
    chatId: XXXXXXXXX # Contact name, user id or chat id
    lang: ru # Or ru, if you drink vodka
    successOnly: false # Set false, if you want receive unsuccessful messages

**Comment by AlexXanderGrib** [comment]
Ты можешь писать на русском и не удалять комментарии, я всё равно их вижу. А проблема скорее всего была с тем, что у тебя неверный `chatId`

**Comment by Strannik74** [comment]
Хорошо. Просто я нашел ошибку самостоятельно и удалил коммент.
Ошибка была в том что я нарушил расположение в коде

vkcc: 
    tokens: [] # Default tokens for links shortening (can also be apps & groups)
    enabled: true

  telegram: # Module for telegram, uncommment for enable
    token: 1391269720:AAGAaCf75u1wOkhPIEF91S7tu6fAsv70YK0 # Telegram bot token, got from BotFather
    chatId: 262346522 # Contact name, user id or chat id
    lang: ru # Or ru, if you drink vodka
    successOnly: true # Set false, if you want receive unsuccessful messages

**Comment by Strannik74** [comment]
vkcc:
telegram: # Module for telegram, uncommment for enable
Должны быть на одном уровне, а я когда удалял # чуток сдвинул telegram: вот скрипт и неотстукивал в телегу
Сейчас все норм. Спасибо тебе! Отличная прога

**Comment by AlexXanderGrib** [comment]
Кста токен от бота поменяй))
